ARG DISTRO="ubuntu"
ARG VERSION="latest"
ARG GUNBOTVERSION="latest"
ARG GITHUBOWNER="GuntharDeNiro"
ARG GITHUBREPO="BTCT"

FROM alpine:latest AS gunbot-builder
ARG GUNBOTVERSION
ARG GITHUBOWNER
ARG GITHUBREPO

WORKDIR /tmp

RUN apk update \
  && apk add --no-cache wget jq unzip \
  && rm -rf /var/lib/apt/lists/* \
  && wget -q -nv -O gunbot.zip $(wget -q -nv -O- https://api.github.com/repos/${GITHUBOWNER}/${GITHUBREPO}/releases/${GUNBOTVERSION} 2>/dev/null | jq -r '.assets[] | select(.browser_download_url | contains("lin")) | .browser_download_url') \
  && unzip -d . gunbot.zip \
  && mv lin* gunbot


FROM ${DISTRO}:${VERSION}
ARG DISTRO
ARG VERSION
ARG GUNBOTVERSION

LABEL \
  maintainer="computeronix" \
  website="https://aka.wf/ai6" \
  description="docker file ${DISTRO} - ${VERSION}, install gunbot version - builder - ${GUNBOTVERSION}"

COPY --from=gunbot-builder /tmp/gunbot /opt/gunbot

#provide script as CMD, accept parameters
#CMD chronyd

#HEALTHCHECK --interval=60s --timeout=5s \
#  CMD chronyc tracking || exit 1
