ARG DISTRO="ubuntu" AS gunbot-builder
ARG VERSION="latest"
ARG GUNBOTVERSION="latest"
ARG GITHUBOWNER="GuntharDeNiro"
ARG GITHUBREPO="BTCT"
FROM ${DISTRO}:${VERSION}
ARG DISTRO
ARG VERSION
ARG GUNBOTVERSION
ARG GITHUBOWNER
ARG GITHUBREPO

LABEL \
  maintainer="computeronix" \
  website="https://aka.wf/ai6" \
  description="docker file ${DISTRO} - ${VERSION}, install gunbot version - builder - ${GUNBOTVERSION}"

WORKDIR /tmp

RUN apt-get update \
  && apt-get -y install wget jq unzip \
  && rm -rf /var/lib/apt/lists/*

RUN wget -q -nv -O gunbot.zip $(wget -q -nv -O- https://api.github.com/repos/${GITHUBOWNER}/${GITHUBREPO}/releases/${GUNBOTVERSION} 2>/dev/null | jq -r '.assets[] | select(.browser_download_url | contains("lin")) | .browser_download_url')
RUN unzip -d gunbot gunbot.zip

#RUN install gunbot oneclick setup sh
#ADD eventually URL
#ADD gunbot_oneclick.sh /tmp/gunbot_oneclick.sh
#RUN .\gunbot_oneclick.sh


#CMD chronyd

#HEALTHCHECK --interval=60s --timeout=5s \
#  CMD chronyc tracking || exit 1
