- name: Fork Sync
  # You may pin to the exact commit or the version.
  # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
  
  on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
  
   - uses: tgymnich/fork-sync@v1.2.1
      with:
        # Owner of the forked repository
        owner: computeronix # optional
        # Token for the github API
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Branch to track
        head: master # optional, default is master
        # Branch to keep updated
        base: master # optional, default is master
        # Merge method to use
        merge_method: merge # optional, default is merge
        # The title of the pull request
        pr_title: Fork Sync # optional, default is Fork Sync
        # The message in the pull request
        pr_message: Updated release from forked release # optional
        # ignore Exceptions
        ignore_fail: # optional
        auto_approve: true
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
